### ISSUE TITLE
Authenticate user

### ISSUE THREAD

**Issue by m-aliozkaya** [salihozkara/GitHunter#17]
If the user wants to increase the rate limit, he should be able to authenticate.

For unauthenticated requests, the rate limit is up to 60 requests per hour, while for authenticated requests up to 5000 requests per hour.
https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#requests-from-personal-accounts

**Comment by salihozkara** [comment]
https://github.com/salihozkara/GitHunter/blob/master/src/GitHunter.Application.Shared/Git/IGitManager.cs#L8-L9
